# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'pluralsight-linux'
  demands: 
  - Agent.OS -equals Linux

steps:
  - task: Bash@3
    displayName: 'Execute Inline Shell Script'
    inputs: 
      targetType: inline
      script: cd spring-boot-basic-microservice/spring-boot-microservice-currency-conversion-service && mvn clean install  -DskipTests
